### ISSUE TITLE
HTTPSConnectionPool

### ISSUE THREAD

**Issue by aldervall** [lindell/home-assistant-tv4-play#10]
Hi,
 
Iam getting this SSL error when iam running TV4.play automation.

Stopped because an error was encountered at 9 september 2022 06:29:38 (runtime: 0.03 seconds)

HTTPSConnectionPool(host='tv4-graphql-web.b17g.net', port=443): Max retries exceeded with url: /graphql (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)')))

**Comment by lindell** [comment]
Thanks for the report.
Please update to 1.1.1 and verify if it works.

It seems TV4 updated their API URL to their own domain, and let the SSL certificate on the old one expire.
