### ISSUE TITLE
Anyone know what to use on Nyhetsmorgon now?

### ISSUE THREAD

**Issue by Hellis81** [lindell/home-assistant-tv4-play#14]
I used to use "Nyhetsmorgon" as the program name but now that doesn´t work anymore.
Looking at tv4play the program name seems to have changed.

![image](https://github.com/lindell/home-assistant-tv4-play/assets/61010215/a0ef9076-5c9b-4789-965c-4b9364128322)

But that does not work either.
Anyone figured it out?

**Comment by Hellis81** [comment]
I just realised something. 
This morning it worked fine, but now I want to start the same episode again and it doesn't work.

Could it be because the page now lists tomorrows episode already?

![image](https://github.com/lindell/home-assistant-tv4-play/assets/61010215/d5873ecc-2d8e-4ccd-93ef-c0a54241dc8e)


Wait, no that isn't the case it seems.
![image](https://github.com/lindell/home-assistant-tv4-play/assets/61010215/f685992c-8981-4550-82eb-5e0528bde60b)

The TV itself is just black, nothing is happening.

**Comment by svemat01** [comment]
Hey, have you found anything more regarding this?

**Comment by lindell** [comment]
Tv4 play does as @Hellis81 write, suggest tomorrows episode. And the service tv4_play.play_suggested does as the name implies, play the suggested episode. 

A new service to play the last one instead could be created and would be happy to merge it. But I think that should be a separate discussion.

**Comment by Hellis81** [comment]
So the proper fix on this is to ask TV4 to not suggest an episode that does not exist yet?
I don't mind sending the "bug" report to them but I don't know the mechanics of the play_suggested. Is this something that tv4play has?

**Comment by lindell** [comment]
I think the solution should be to add tv4_play.play_latest. I'm happy to merge a pull request. Otherwise, please add it as a new issue for someone else to add. I will probably come around to adding it, but it will not be in the near future.
