### ISSUE TITLE
No 'version' key in the manifest file

### ISSUE THREAD

**Issue by mnil** [lindell/home-assistant-tv4-play#6]
Verkar som att den kommer sluta fungera om du inte lägger till version's fältet i manifestet:
https://developers.home-assistant.io/docs/creating_integration_manifest/#version

`2021-04-20 09:56:38 WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'tv4_play'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'tv4_play'`

**Comment by lindell** [comment]
It should now be added. Could you please update and confirm 🙂

**Comment by mnil** [comment]
Thanks for quick feedback, the fix seems to work! Thanks for a really handy application!
