### ISSUE TITLE
TV4 Nyhetsmorgon does not play

### ISSUE THREAD

**Issue by nolenjohan** [lindell/home-assistant-tv4-play#9]
When trying to start TV4 Nyhetsmorgon using the same method since over a year (a preconfigured button), to play on my Nest Hub Max, it's only showing the light blue Home Assistant screen  ("Welcome to Home Assistant"). The same on my other screeen, a Nest Hub, using the same pre-configured button.

Other programs, like "nyheterna" is working as expected, it's just "nyhetsmorgon" that doesn't work since a week or so.

type: button
icon: mdi:youtube-tv
name: TV4 Nyhetsmorgon
show_icon: true
show_name: true
double_tap_action:
  action: call-service
  service: tv4_play.play_suggested
  service_data:
    entity_id: media_player.matrummet_nest_hub_max
    program_name: nyhetsmorgon
show_state: true

**Comment by mnil** [comment]
I am having the same problem. Could it be that something change in HA 2021.12?

**Comment by lindell** [comment]
I just tried it myself. Both on 2021.11 since I hadn't update yet, and on 2021.12, and both worked 🤔
![image](https://user-images.githubusercontent.com/284868/146683913-3c835063-8809-4c44-af22-4e4fb2730f67.png)

But this was not during a live broadcast. @nolenjohan @mnil does it work for you after the fact?

It seems that it is at least grabbing **an** URL at least during the morning since daily tests are passing.
https://github.com/lindell/home-assistant-tv4-play/blob/master/custom_components/tv4_play/video_url_fetch/morning_test.py

**Comment by mnil** [comment]
I tested this morning again with the developer tools and got the same result, first it appears to load "nyhetsmorgon" but then the "Welcome to Home Assistant" screen appears. I also tested with "nyheterna" which works fine.
```
service: tv4_play.play_suggested
data:
  entity_id: media_player.living_room_tv
  program_name: nyhetsmorgon
```

**Comment by lindell** [comment]
I tried it as well during the morning and it did not work for me neither.

Had a quick look at the tv4play website, and I might have found the cause, and it does not look promising. 
I does seem like TV4 has added some kind of DRM to their livestreams. But I need to look more into this.
![image](https://user-images.githubusercontent.com/284868/146728128-d3db07d7-917a-4785-87aa-42a86f28dafd.png)

**Comment by mnil** [comment]
@lindell hasn't widewine been there all along?
`url = 'https://playback-api.b17g.net/media/{}?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine&is_live={}&has_startover={}'.format(`
https://github.com/lindell/home-assistant-tv4-play/blob/master/custom_components/tv4_play/video_url_fetch/video_fetch.py#L7

**Comment by lindell** [comment]
Seems like it 🤦 

Just didn't recognize it and assumed since I also couldn't play the URL directly from the website in VLC neither. I don't have the time to look more at it now, but will try to do it later. If you are able to fetch a link that is playable, please write about it in this issue 🙂

**Comment by mnil** [comment]
@lindell @nolenjohan This problem has been solved in 2021.12.4, updated yesterday and confirmed today.
> Don’t use the homeassistant media app when casting media (@emontnemery - [#62385](https://github.com/home-assistant/core/pull/62385)) ([cast docs](https://www.home-assistant.io/integrations/cast/))

https://www.home-assistant.io/blog/2021/12/11/release-202112/#release-2021124---december-20

**Comment by aldervall** [comment]
Hi @lindell,

I was about to send a long trail of investigation on why TV4 nyhetsmorgon diden´t work.
I did not check if TV4 actually had "summer time" on their schedule. (Stream starts 06:45 instead of 05:45)

Thank you for a wonderful working automation! Kudos!

**Comment by lindell** [comment]
> I was about to send a long trail of investigation on why TV4 nyhetsmorgon diden´t work.
I did not check if TV4 actually had "summer time" on their schedule. (Stream starts 06:45 instead of 05:45)

Had the same experience the first year of running a morning routine that started nyhetsmorgon 😛 

> Thank you for a wonderful working automation! Kudos!

Thanks :)
